tt20

diff --git a/.github/workflows/freertos_demos.yml b/.github/workflows/freertos_demos.yml
--- a/.github/workflows/freertos_demos.yml
+++ b/.github/workflows/freertos_demos.yml
@@ -83,17 +83,29 @@ jobs:
         continue-on-error: true
 
       - name: Check output of FullDemo
-        working-directory: FreeRTOS/Demo/Posix_GCC
-        run: |
-          set -e
-          if grep -q "OK: No errors" output.txt; then
-            echo -e "\nSUCCESS - Found SUCCESS string in output."
-          else
-            echo -e "\nFAILURE - SUCCESS string not found in output."
-            exit 1
-          fi
-        if: always()
+        id: check-output
+        uses: actions/github-script@v4
+        with:
+          script: |
+            const fs = require('fs');
+            const output = fs.readFileSync('output.txt', 'utf8');
+            if (!output.includes('OK: No errors')) {
+              return { state: 'failure', description: 'String not found' };
+            } else {
+              return { state: 'success' };
+            }
         continue-on-error: true
+        # working-directory: FreeRTOS/Demo/Posix_GCC
+        # run: |
+        #   set -e
+        #   if grep -q "OK: No errors" output.txt; then
+        #     echo -e "\nSUCCESS - Found SUCCESS string in output."
+        #   else
+        #     echo -e "\nFAILURE - SUCCESS string not found in output."
+        #     exit 1
+        #   fi
+        # if: always()
+        # continue-on-error: true
 
       - name: Build Posix_GCC Blinky Demo
         shell: bash
