update http demos

diff --git a/.github/workflows/freertos_plus_demos.yml b/.github/workflows/freertos_plus_demos.yml
--- a/.github/workflows/freertos_plus_demos.yml
+++ b/.github/workflows/freertos_plus_demos.yml
@@ -108,18 +108,6 @@ jobs:
           meson setup build --backend=vs2019
           meson compile -C build
 
-      - name: Generate SSL credentials
-        id: generate-credentials
-        uses: FreeRTOS/CI-CD-GitHub-Actions/ssl-credential-creator@main
-
-      - name: Start localhost HTTP server
-        id: http-server
-        uses: FreeRTOS/CI-CD-GitHub-Actions/localhost-http-1.1-server@main
-        with:
-          root-ca-cert-path: ${{ steps.generate-credentials.outputs.root-ca-cert-path }}
-          server-priv-key-path: ${{ steps.generate-credentials.outputs.server-priv-key-path }}
-          server-cert-path: ${{ steps.generate-credentials.outputs.server-cert-path }}
-
       - name: Update main.c to force stdout to write immediately
         working-directory: FreeRTOS-Plus/Demo/coreHTTP_Windows_Simulator/Common
         run: |
@@ -264,16 +252,27 @@ jobs:
           aws iot detach-thing-principal --thing-name ${{ env.IOT_THING_NAME }} --principal $certificateArn
           aws iot delete-certificate --certificate-id $certificateId
 
+      - name: Generate SSL credentials
+        id: generate-credentials
+        uses: FreeRTOS/CI-CD-GitHub-Actions/ssl-credential-creator@main
+
+      - name: Start localhost HTTP server
+        id: http-server
+        uses: FreeRTOS/CI-CD-GitHub-Actions/localhost-http-1.1-server@main
+        with:
+          root-ca-cert-path: ${{ steps.generate-credentials.outputs.root-ca-cert-path }}
+          server-priv-key-path: ${{ steps.generate-credentials.outputs.server-priv-key-path }}
+          server-cert-path: ${{ steps.generate-credentials.outputs.server-cert-path }}
+
       - name: Configure HTTP Plain Text Demo
-        if: success() || failure()
         shell: bash
         working-directory: FreeRTOS-Plus/Demo/coreHTTP_Windows_Simulator/HTTP_Plaintext
         run: |
-          echo '#define democonfigSERVER_HOSTNAME "127.0.0.1"' >> demo_config.h
-          echo '#define democonfigHTTP_PORT ( 8080 )' >> demo_config.h
+          echo '#undef democonfigHTTP_PORT' >> demo_config.h
+          echo '#define democonfigSERVER_HOSTNAME "httpbin.org"' >> demo_config.h
+          echo '#define democonfigHTTP_PORT ( 80 )' >> demo_config.h
 
       - name: Build HTTP Plain Text Demo
-        if: success() || failure()
         id: build-http-plain-text-demo
         working-directory: FreeRTOS-Plus/Demo/coreHTTP_Windows_Simulator/HTTP_Plaintext
         run: msbuild http_plain_text_demo.sln -t:rebuild -property:Configuration=Debug -property:Platform=x64 -m
@@ -290,7 +289,6 @@ jobs:
 
       - name: Configure HTTP Mutual Auth Demo
         shell: bash
-        if: success() || failure()
         working-directory: FreeRTOS-Plus/Demo/coreHTTP_Windows_Simulator/HTTP_Mutual_Auth
         run: |
           echo '#define democonfigROOT_CA_PEM \' >> demo_config.h
@@ -307,20 +305,19 @@ jobs:
           sed -i -z "s/define[[:space:]]*democonfigDISABLE_SNI[[:space:]]*([[:space:]]*[a-zA-Z0-9]\+[[:space:]]*)/define democonfigDISABLE_SNI ( pdTRUE )/g" demo_config.h
 
       - name: Build HTTP Mutual Auth Demo
-        if: success() || failure()
         id: build-http-mutual-auth-demo
         working-directory: FreeRTOS-Plus/Demo/coreHTTP_Windows_Simulator/HTTP_Mutual_Auth
         run: msbuild http_mutual_auth_demo.sln -t:rebuild -property:Configuration=Debug -property:Platform=x64 -m
 
-      - name: Run and monitor HTTP Mutual Auth Demo
-        if: success() || failure() && steps.build-http-mutual-auth-demo.outcome == 'success'
-        uses: FreeRTOS/CI-CD-GitHub-Actions/executable-monitor@406befbab928397abaa8fe2c210dcbc731856ff0
-        with:
-          exe-path: FreeRTOS-Plus/Demo/coreHTTP_Windows_Simulator/HTTP_Mutual_Auth/x64/Debug/CoreHTTP_Mutual_Auth.exe
-          log-dir: demo_run_logs
-          timeout-seconds: 300
-          success-line: "Demo completed successfully"
-          retry-attempts: 2
+      # - name: Run and monitor HTTP Mutual Auth Demo
+      #   if: success() || failure() && steps.build-http-mutual-auth-demo.outcome == 'success'
+      #   uses: FreeRTOS/CI-CD-GitHub-Actions/executable-monitor@406befbab928397abaa8fe2c210dcbc731856ff0
+      #   with:
+      #     exe-path: FreeRTOS-Plus/Demo/coreHTTP_Windows_Simulator/HTTP_Mutual_Auth/x64/Debug/CoreHTTP_Mutual_Auth.exe
+      #     log-dir: demo_run_logs
+      #     timeout-seconds: 300
+      #     success-line: "Demo completed successfully"
+      #     retry-attempts: 2
 
   winsim_corePKCS11:
     name: corePKCS11 WinSim Demos
