tt22

diff --git a/.github/workflows/freertos_demos.yml b/.github/workflows/freertos_demos.yml
--- a/.github/workflows/freertos_demos.yml
+++ b/.github/workflows/freertos_demos.yml
@@ -78,34 +78,13 @@ jobs:
         if: success() || failure() && steps.build-posix-gcc-demo.outcome == 'success'
         working-directory: FreeRTOS/Demo/Posix_GCC
         run: |
-          set -e
-          timeout 30s build/posix_demo | tee output.txt
-        continue-on-error: true
-
-      - name: Check output of FullDemo
-        id: check-output
-        uses: actions/github-script@v4
-        with:
-          script: |
-            const fs = require('fs');
-            const output = fs.readFileSync('FreeRTOS/Demo/Posix_GCC/output.txt', 'utf8');
-            if (!output.includes('OK: No errors')) {
-              return { state: 'failure', description: 'String not found' };
-            } else {
-              return { state: 'success' };
-            }
-        continue-on-error: true
-        # working-directory: FreeRTOS/Demo/Posix_GCC
-        # run: |
-        #   set -e
-        #   if grep -q "OK: No errors" output.txt; then
-        #     echo -e "\nSUCCESS - Found SUCCESS string in output."
-        #   else
-        #     echo -e "\nFAILURE - SUCCESS string not found in output."
-        #     exit 1
-        #   fi
-        # if: always()
-        # continue-on-error: true
+          timeout 3m build/posix_demo | tee output.txt
+          if grep -q "OK: No errors" output.txt; then
+            echo -e "\nSUCCESS - Found SUCCESS string in output."
+          else
+            echo -e "\nFAILURE - SUCCESS string not found in output."
+            exit 1
+          fi
 
       - name: Build Posix_GCC Blinky Demo
         shell: bash
