test run win32-msvc demo

diff --git a/.github/workflows/freertos_demos.yml b/.github/workflows/freertos_demos.yml
--- a/.github/workflows/freertos_demos.yml
+++ b/.github/workflows/freertos_demos.yml
@@ -20,8 +20,21 @@ jobs:
         uses: microsoft/setup-msbuild@v1.1
 
       - name: Build WIN32-MSVC Demo
+        id: build-win32-msvs-demo
         working-directory: FreeRTOS/Demo/WIN32-MSVC
         run: msbuild WIN32.sln -t:rebuild
+
+      - name: Run and monitor WIN32-MSVC Demo
+        if: success() || failure() && steps.build-win32-msvs-demo.outcome == 'success'
+        working-directory: FreeRTOS/Demo/WIN32-MSVC
+        run: |
+          timeout 2m Debug/RTOSDemo | tee output.txt
+          if grep -q "No errors" output.txt; then
+            echo -e "\nSUCCESS - Found SUCCESS string in output."
+          else
+            echo -e "\nFAILURE - SUCCESS string not found in output."
+            exit 1
+          fi
 
       - name: Build WIN32-MSVC-Static-Allocation-Only Demo
         working-directory: FreeRTOS/Demo/WIN32-MSVC-Static-Allocation-Only
