Fix an issue in the CMAKE files, tweak to the github build workflow

diff --git a/.github/workflows/freertos_mpu_demo.yml b/.github/workflows/freertos_mpu_demo.yml
--- a/.github/workflows/freertos_mpu_demo.yml
+++ b/.github/workflows/freertos_mpu_demo.yml
@@ -11,8 +11,8 @@ env:
   bashEnd:  \033[0m
 
 jobs:
-  ARMv7-R:
-    name: GNU ARM Toolchain
+  Cortex-R4:
+    name: Texas Instruments RM46
     runs-on: ubuntu-latest
     steps:
       - env:
@@ -35,10 +35,10 @@ jobs:
           echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
 
       - env:
-          stepName: Build CORTEX R5 MPU Demo
+          stepName: Build CORTEX R4 MPU Demo
         name: ${{ env.stepName }}
         shell: bash
-        working-directory: FreeRTOS/Demo/CORTEX_R5_RM57_HERCULES_MCU_GCC
+        working-directory: FreeRTOS/Demo/CORTEX_R4_RM46_HERCULES_MCU_GCC
         run: |
           # ${{ env.stepName }}
           echo -e "::group::${{ env.bashInfo }} ${{ env.stepName }} ${{ env.bashEnd }}"
@@ -55,11 +55,53 @@ jobs:
             exit 1
           fi
 
+  Cortex-R5:
+    name: Texas Instruments RM57
+    runs-on: ubuntu-latest
+    steps:
       - env:
-          stepName: Build CORTEX R4 MPU Demo
+          stepName: Checkout Repository
+        name: ${{ env.stepName }}
+        uses: actions/checkout@v3
+        with:
+          submodules: false
+
+      - env:
+          stepName: Install GNU ARM Toolchain
+        name: Install GNU ARM Toolchain
+        shell: bash
+        run: |
+          # ${{ env.stepName }}
+          echo -e "::group::${{ env.bashInfo }} ${{ env.stepName }} ${{ env.bashEnd }}"
+          sudo apt-get -y update
+          sudo apt-get -y install gcc-arm-none-eabi build-essential cmake git ninja-build python3-minimal
+          echo -e "::endgroup::"
+          echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
+
+      - env:
+          stepName: Fetch Kernel Submodule
         name: ${{ env.stepName }}
         shell: bash
-        working-directory: FreeRTOS/Demo/CORTEX_R4_RM46_HERCULES_MCU_GCC
+        run: |
+          # ${{ env.stepName }}
+          echo -e "::group:: ${{ env.bashInfo }} ${{ env.stepName }} ${{ env.bashEnd }}"
+          set +e
+          git submodule update --checkout --init --depth 1 FreeRTOS/Source FreeRTOS/Demo/ThirdParty/Community-Supported-Demos
+          exitStatus=$?
+          set -e
+          echo -e "::endgroup::"
+          if [ $exitStatus -eq 0 ]; then
+            echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
+          else
+            echo -e "${{ env.bashFail }} ${{ env.stepName }} ${{ env.bashEnd }}"
+            exit 1
+          fi
+
+      - env:
+          stepName: Build CORTEX R5 MPU Demo
+        name: ${{ env.stepName }}
+        shell: bash
+        working-directory: FreeRTOS/Demo/CORTEX_R5_RM57_HERCULES_MCU_GCC
         run: |
           # ${{ env.stepName }}
           echo -e "::group::${{ env.bashInfo }} ${{ env.stepName }} ${{ env.bashEnd }}"
