try direct

diff --git a/.github/workflows/freertos_demos.yml b/.github/workflows/freertos_demos.yml
--- a/.github/workflows/freertos_demos.yml
+++ b/.github/workflows/freertos_demos.yml
@@ -71,18 +71,26 @@ jobs:
       - name: Build Posix_GCC Demo
         shell: bash
         working-directory: FreeRTOS/Demo/Posix_GCC
+        # sed -i "s/#define[[:space:]]\+mainSELECTED_APPLICATION[[:space:]]\+FULL_DEMO/#define    mainSELECTED_APPLICATION      BLINKY_DEMO/g" main.c
         run: |
-          sed -i "s/#define[[:space:]]\+mainSELECTED_APPLICATION[[:space:]]\+FULL_DEMO/#define    mainSELECTED_APPLICATION      BLINKY_DEMO/g" main.c
           make -j
 
       - name: Run and monitor Posic_GCC Demo
         if: success() || failure() && steps.build-posix-gcc-demo.outcome == 'success'
-        uses: FreeRTOS/CI-CD-GitHub-Actions/executable-monitor@p3run
-        with:
-          exe-path: FreeRTOS/Demo/Posix_GCC/build/posix_demo
-          log-dir: FreeRTOS/Demo/Posix_GCC/build/demo_run_logs
-          timeout-seconds: 60
-          success-line: "Message received from software timer"
+        run: |
+          ./build/posix_demo > output.txt
+          if grep -q "OK: No errors" output.txt; then
+            echo "Found string in output file."
+          else
+            echo "String not found in output file. Exiting with error."
+            exit 1
+          fi
+        # uses: FreeRTOS/CI-CD-GitHub-Actions/executable-monitor@p3run
+        # with:
+        #   exe-path: FreeRTOS/Demo/Posix_GCC/build/posix_demo
+        #   log-dir: FreeRTOS/Demo/Posix_GCC/build/demo_run_logs
+        #   timeout-seconds: 60
+        #   success-line: "Message received from software timer"
 
 
   MSP430-GCC:
