tt5

diff --git a/.github/workflows/freertos_demos.yml b/.github/workflows/freertos_demos.yml
--- a/.github/workflows/freertos_demos.yml
+++ b/.github/workflows/freertos_demos.yml
@@ -79,15 +79,13 @@ jobs:
         if: success() || failure() && steps.build-posix-gcc-demo.outcome == 'success'
         working-directory: FreeRTOS/Demo/Posix_GCC
         run: |
-          pwd
-          build/posix_demo 
-        # > output.txt
-        # if grep -q "OK: No errors" output.txt; then
-        #   echo "Found string in output file."
-        # else
-        #   echo "String not found in output file. Exiting with error."
-        #   exit 1
-        # fi
+          timeout 5m build/posix_demo > output.txt
+          if grep -q "OK: No errors" output.txt; then
+            echo "Found string in output file."
+          else
+            echo "String not found in output file. Exiting with error."
+            exit 1
+          fi
         # uses: FreeRTOS/CI-CD-GitHub-Actions/executable-monitor@p3run
         # with:
         #   exe-path: FreeRTOS/Demo/Posix_GCC/build/posix_demo
